title: Ajit Kolekar
author: Ajit Kolekar
mailto: ajit.kolekar18@gmail.com

description: >
<br><br>
Aboutme: 
 <br>
I'm a well rounded IT professional with 23+ years of experience. I'm currently serving at State Farm Insurance as a Scrum Master. I have a variety of technical, 
business, and leadership experience while performing roles as Project Manager, Scrum Master, Team Lead, Data Analyst, Java Developer, Host Developer, Subject Matter 
Consultant, Systems Analyst, Service Analyst, and Onsite-Offshore Coordinator.
<br>
I have earned my Bachelors Degree in Electronics Engineering, Masters of Business Administation, and am currently working on Masters of Science in Data Science 
degree with expected completion date less than two months away! I believe in continuous learning and have earned several designations and certifications, such as 
PMP, CSM, SAFe Agilist, SASM, CPCU, ChFC, CLU, and AWS Certified Cloud Practitioner.
<br>

theme: jekyll-theme-minimal
