title: Ajit Kolekar
social-network-links:
  email: "ajit.kolekar18@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: ajitkolekar
  twitter: ajitkolekar
  linkedin: ajit-kolekar-52229779

share-links-active:
  email: true
  twitter: true
  github: true
  linkedin: true
#tagline: Data Science Projects Portfolio
#author: Ajit Kolekar
#description: > 
#  About Me: 
#  <br>
#  I'm a well rounded IT professional with 23+ years of experience. I'm currently serving at State Farm Insurance as a Scrum Master. I have a variety of technical, business, and leadership experience while performing roles as Project Manager, Scrum Master, Team Lead, Data Analyst, Java Developer, Host Developer, Subject Matter Consultant, Systems Analyst, Service Analyst, and Onsite-Offshore Coordinator.
#  <br><br>
#  I have earned my Bachelors Degree in Electronics Engineering, Masters of Business Administation, and am currently working on Masters of Science in Data Science degree with expected completion date less than two months away! I believe in continuous learning and have earned several designations and certifications, such as PMP, CSM, SAFe Agilist, SASM, CPCU, ChFC, CLU, and AWS Certified Cloud Practitioner.
#  <br><br>
email: ajit.kolekar18@gmail.com
twitter_username: ajitkolekar  
github_username:  ajitkolekar
ShowContactInfo: "True"
default_column: "one"
theme: jekyll-theme-minimal
