title: Ajit Kolekar
tagline: Data Science Projects Portfolio
description: 
  <img align="center" src="../images/Ajit.JPG " width="200" height="225" />
  <br/>
  <br/>
  <a href="/about.html">About Me</a> | <a href="/contact.html">Contact</a> | <a href="/docs/resume.pdf">Resume</a> 

author:
  name:  Ajit Kolekar
  email: ajit.kolekar18@gmail.com
  social:
    github:  ajitkolekar
    twitter: ajitkolekar
#social-network-links:
#  email: "ajit.kolekar18@gmail.com"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  github: ajitkolekar
#  twitter: ajitkolekar
#  linkedin: ajit-kolekar-52229779

#share-links-active:
#  email: true
#  twitter: true
#  github: true
#  linkedin: true

email: ajit.kolekar18@gmail.com
twitter_username: ajitkolekar  
github_username:  ajitkolekar
ShowContactInfo: "True"
default_column: "one"
theme: jekyll-theme-minimal
