title: Ajit Kolekar
tagline: Data Science Projects Portfolio
author: Ajit Kolekar
email: ajit.kolekar18@gmail.com
twitter_username: ajitkolekar  
github_username:  ajitkolekar
ShowContactInfo: "True"
theme: jekyll-theme-minimal
