title: Ajit Kolekar
tagline: Data Science Projects Portfolio
description: 
  <img align="center" src="../images/Ajit.JPG " width="200" height="225" />
  <br/>
  <br/>
  <a href="/about.html">About Me</a> | <a href="/contact.html">Contact</a> | <a href="/docs/resume.pdf" target="_blank">Resume</a>
  <br/>
  <br/>
  <a href="https://linkedin.com/in/ajit-kolekar-52229779/" target="_blank">
    <img src="images/linkedin.png" width="50" height="50" /></a>
  &nbsp;&nbsp;&nbsp;
  <a href="https://www.twitter.com/ajitkolekar" target="_blank">
    <img src="images/twitter.png" width="50" height="50" /></a>
  &nbsp;&nbsp;&nbsp;
  <a href="https://www.facebook.com/ajit.kolekar" target="_blank">
    <img src="images/facebook.png" width="50" height="50" /></a>
  <br/>
  <h3>Data Science Skills</h3>
  <p>Python Programming&#10;&#13;R Programming&#10;Data Preparation (Wrangling), Data Mining, Exploratory Data Analysis, 
  Predictive Analytics, Machine Learning, Data Visualization, and Big Data</p>

theme: jekyll-theme-minimal
